# Generated by Django 3.0.4 on 2020-03-18 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.FloatField(db_column='IdTweet')),
                ('text', models.TextField(blank=True, db_column='TweetText', null=True)),
                ('created_at', models.DateTimeField(db_column='TimeCreated', default=django.utils.timezone.now)),
                ('re_tweet_count', models.BigIntegerField(blank=True, db_column='RetweetCount', null=True)),
                ('favorite_count', models.BigIntegerField(blank=True, db_column='FavoriteCount', null=True)),
                ('urls', models.TextField(blank=True, db_column='Urls', null=True)),
                ('medias', models.TextField(blank=True, db_column='Medias', null=True)),
                ('tags', models.TextField(blank=True, db_column='Tags', null=True)),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
                'db_table': 'Tweets',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
